name: Java CI with Maven

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    
    # Set up matrix for different operating systems
    runs-on: ubuntu-latest

    # Set up JDK 17
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    
    # Build with Maven 
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    # Save the JAR file as an artifact
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: Sum
        path: target/*.jar